"use client";

// ── Body zones ──
export const BODY_ZONES = [
  { id: "face", label: "面", emoji: "😊" },
  { id: "neck", label: "頸", emoji: "🦒" },
  { id: "chest", label: "胸口", emoji: "👕" },
  { id: "back", label: "背", emoji: "🔙" },
  { id: "left_arm", label: "左手", emoji: "💪" },
  { id: "right_arm", label: "右手", emoji: "💪" },
  { id: "left_hand", label: "左手掌", emoji: "🤚" },
  { id: "right_hand", label: "右手掌", emoji: "🤚" },
  { id: "abdomen", label: "肚", emoji: "🫃" },
  { id: "left_leg", label: "左腳", emoji: "🦵" },
  { id: "right_leg", label: "右腳", emoji: "🦵" },
  { id: "left_foot", label: "左腳掌", emoji: "🦶" },
  { id: "right_foot", label: "右腳掌", emoji: "🦶" },
  { id: "scalp", label: "頭皮", emoji: "🧠" },
  { id: "ears", label: "耳", emoji: "👂" },
  { id: "groin", label: "腹股溝", emoji: "🔻" },
  { id: "elbows", label: "手踭", emoji: "💍" },
  { id: "knees", label: "膝頭", emoji: "🦿" },
] as const;

// ── Sub-locations for each body zone ──
export const SUB_LOCATIONS: Record<string, { id: string; label: string; emoji: string }[]> = {
  face: [
    { id: "forehead", label: "額頭", emoji: "🧑" },
    { id: "eyelids", label: "眼皮", emoji: "👁️" },
    { id: "cheeks", label: "面頰", emoji: "😊" },
    { id: "nose", label: "鼻", emoji: "👃" },
    { id: "lips", label: "嘴唇", emoji: "👄" },
    { id: "chin", label: "下巴", emoji: "🫦" },
    { id: "jawline", label: "下顎", emoji: "🦴" },
    { id: "around_ears", label: "耳後", emoji: "👂" },
  ],
  neck: [
    { id: "front", label: "頸前", emoji: "🔄" },
    { id: "back", label: "頸後", emoji: "🔙" },
    { id: "sides", label: "兩側", emoji: "↔️" },
  ],
  scalp: [
    { id: "top", label: "頭頂", emoji: "🔝" },
    { id: "temples", label: "太陽穴", emoji: "⬅️" },
    { id: "back_of_head", label: "後尾枕", emoji: "🔙" },
    { id: "hairline", label: "髮際", emoji: "〰️" },
  ],
  ears: [
    { id: "earlobe", label: "耳垂", emoji: "💎" },
    { id: "outer_ear", label: "外耳", emoji: "👂" },
    { id: "behind_ear", label: "耳後", emoji: "🔙" },
  ],
  chest: [
    { id: "upper_chest", label: "上胸", emoji: "⬆️" },
    { id: "center", label: "胸口中央", emoji: "🎯" },
    { id: "collarbone", label: "鎖骨", emoji: "🦴" },
  ],
  back: [
    { id: "upper_back", label: "上背", emoji: "⬆️" },
    { id: "mid_back", label: "中背", emoji: "↕️" },
    { id: "lower_back", label: "下背", emoji: "⬇️" },
    { id: "shoulder_blades", label: "肩胛骨", emoji: "🦴" },
  ],
  abdomen: [
    { id: "upper", label: "上腹", emoji: "⬆️" },
    { id: "lower", label: "下腹", emoji: "⬇️" },
    { id: "navel_area", label: "肚臍周圍", emoji: "🎯" },
    { id: "sides", label: "兩側", emoji: "↔️" },
  ],
  left_arm: [
    { id: "shoulder", label: "肩膀", emoji: "🤷" },
    { id: "upper_arm_outer", label: "上臂外側", emoji: "↗️" },
    { id: "upper_arm_inner", label: "上臂內側", emoji: "↙️" },
    { id: "forearm_outer", label: "前臂外側", emoji: "↗️" },
    { id: "forearm_inner", label: "前臂內側", emoji: "↙️" },
    { id: "elbow_crease", label: "手肘摺位", emoji: "📐" },
  ],
  right_arm: [
    { id: "shoulder", label: "肩膀", emoji: "🤷" },
    { id: "upper_arm_outer", label: "上臂外側", emoji: "↗️" },
    { id: "upper_arm_inner", label: "上臂內側", emoji: "↙️" },
    { id: "forearm_outer", label: "前臂外側", emoji: "↗️" },
    { id: "forearm_inner", label: "前臂內側", emoji: "↙️" },
    { id: "elbow_crease", label: "手肘摺位", emoji: "📐" },
  ],
  elbows: [
    { id: "elbow_tip", label: "手踭尖", emoji: "💎" },
    { id: "elbow_crease", label: "摺位", emoji: "📐" },
    { id: "around_elbow", label: "手踭周圍", emoji: "⭕" },
  ],
  left_hand: [
    { id: "palm", label: "手板", emoji: "🤚" },
    { id: "back_of_hand", label: "手背", emoji: "✋" },
    { id: "thumb", label: "拇指", emoji: "👍" },
    { id: "index_finger", label: "食指", emoji: "☝️" },
    { id: "middle_finger", label: "中指", emoji: "🖕" },
    { id: "ring_finger", label: "無名指", emoji: "💍" },
    { id: "little_finger", label: "尾指", emoji: "🤙" },
    { id: "finger_tips", label: "指尖", emoji: "👆" },
    { id: "between_fingers", label: "手指縫", emoji: "🤞" },
    { id: "wrist", label: "手腕", emoji: "⌚" },
    { id: "knuckles", label: "指關節", emoji: "👊" },
  ],
  right_hand: [
    { id: "palm", label: "手板", emoji: "🤚" },
    { id: "back_of_hand", label: "手背", emoji: "✋" },
    { id: "thumb", label: "拇指", emoji: "👍" },
    { id: "index_finger", label: "食指", emoji: "☝️" },
    { id: "middle_finger", label: "中指", emoji: "🖕" },
    { id: "ring_finger", label: "無名指", emoji: "💍" },
    { id: "little_finger", label: "尾指", emoji: "🤙" },
    { id: "finger_tips", label: "指尖", emoji: "👆" },
    { id: "between_fingers", label: "手指縫", emoji: "🤞" },
    { id: "wrist", label: "手腕", emoji: "⌚" },
    { id: "knuckles", label: "指關節", emoji: "👊" },
  ],
  left_leg: [
    { id: "thigh_front", label: "大腿前", emoji: "⬆️" },
    { id: "thigh_back", label: "大腿後", emoji: "🔙" },
    { id: "thigh_inner", label: "大腿內側", emoji: "↙️" },
    { id: "thigh_outer", label: "大腿外側", emoji: "↗️" },
    { id: "shin", label: "脛骨位", emoji: "🦴" },
    { id: "calf", label: "小腿肚", emoji: "💪" },
    { id: "knee_crease", label: "膝蓋後摺位", emoji: "📐" },
  ],
  right_leg: [
    { id: "thigh_front", label: "大腿前", emoji: "⬆️" },
    { id: "thigh_back", label: "大腿後", emoji: "🔙" },
    { id: "thigh_inner", label: "大腿內側", emoji: "↙️" },
    { id: "thigh_outer", label: "大腿外側", emoji: "↗️" },
    { id: "shin", label: "脛骨位", emoji: "🦴" },
    { id: "calf", label: "小腿肚", emoji: "💪" },
    { id: "knee_crease", label: "膝蓋後摺位", emoji: "📐" },
  ],
  knees: [
    { id: "kneecap", label: "膝頭蓋", emoji: "🦴" },
    { id: "knee_crease", label: "膝後摺位", emoji: "📐" },
    { id: "around_knee", label: "膝蓋周圍", emoji: "⭕" },
  ],
  left_foot: [
    { id: "sole", label: "腳板底", emoji: "🦶" },
    { id: "arch", label: "腳拱", emoji: "🏛️" },
    { id: "heel", label: "腳踭", emoji: "🦶" },
    { id: "top_of_foot", label: "腳面", emoji: "⬆️" },
    { id: "ankle", label: "腳踝", emoji: "🦴" },
    { id: "toes", label: "腳趾", emoji: "🦶" },
    { id: "between_toes", label: "腳趾縫", emoji: "🤞" },
  ],
  right_foot: [
    { id: "sole", label: "腳板底", emoji: "🦶" },
    { id: "arch", label: "腳拱", emoji: "🏛️" },
    { id: "heel", label: "腳踭", emoji: "🦶" },
    { id: "top_of_foot", label: "腳面", emoji: "⬆️" },
    { id: "ankle", label: "腳踝", emoji: "🦴" },
    { id: "toes", label: "腳趾", emoji: "🦶" },
    { id: "between_toes", label: "腳趾縫", emoji: "🤞" },
  ],
  groin: [
    { id: "inguinal", label: "腹股溝", emoji: "🔻" },
    { id: "inner_thigh_top", label: "大腿內側頂", emoji: "↙️" },
    { id: "genital_area", label: "生殖器周圍", emoji: "⭕" },
  ],
};

// ── Eczema symptoms (expanded) ──
export const SYMPTOM_OPTIONS = [
  { id: "redness", label: "紅腫", emoji: "🔴", category: "visual" },
  { id: "oozing", label: "滲水", emoji: "💧", category: "visual" },
  { id: "scaling", label: "脫皮", emoji: "🍂", category: "visual" },
  { id: "swelling", label: "腫脹", emoji: "🫧", category: "visual" },
  { id: "blisters", label: "水泡", emoji: "🫧", category: "visual" },
  { id: "dryness", label: "乾燥", emoji: "🏜️", category: "texture" },
  { id: "cracking", label: "龜裂", emoji: "💔", category: "texture" },
  { id: "crusting", label: "結痂", emoji: "🩹", category: "visual" },
  { id: "thickening", label: "增厚", emoji: "🧱", category: "texture" },
  { id: "hyperpigmentation", label: "色素沉澱", emoji: "🟤", category: "visual" },
  { id: "bleeding", label: "出血", emoji: "🩸", category: "severe" },
] as const;

export type SymptomId = (typeof SYMPTOM_OPTIONS)[number]["id"];
